name: "Upload package.json SARIF"
# Run workflow each time code is pushed to your repository.
on: push
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: snyk/actions/setup@master
     - name: Snyk Test
       run: snyk test --all-projects
     - name: Snyk monitor
       run: snyk monitor --all-projects
       continue-on-error: true
       env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
