name: "Upload package.json SARIF"
# Run workflow each time code is pushed to your repository.
on: push
jobs:
 build:
   runs-on: ubuntu-latest
   env:
    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
   steps:
     - uses: actions/checkout@master
     - uses: snyk/actions/setup@master
     - name: Snyk Test
       continue-on-error: true
       run: snyk test --all-projects
     - name: Snyk monitor       
       run: snyk monitor --all-projects       
       
